version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
    networks:
      - bot-network

  bot:
    build: .
    environment:
      DISCORD_TOKEN:
      OPENAI_API_KEY:
      PREMIUM_ROLE_ID:
      DATABASE_URL:
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
